website/auth.py
# Standard library imports
from functools import wraps

# Related third party imports
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash
import paypalrestsdk
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Local application/library specific imports
from . import db
from .models import Cart, Product, User

paypal_client_id = "ATNxeyrcueUk-PfCIq2BFb4Ky8u0Jui6E96nON3-RyEQqw4o2bU-ltr0UxXxXBayyYCg9nPTJZo_JNNi"
paypal_client_secret = "EJ6NGGXgN-dwwTuIhLxqEHo3eS8y-JMSzsK5hgI7GkljBy9uM65pkeYsQwYNWFt2J9seyQunTPeFs-ku"

auth = Blueprint("auth", __name__)

paypalrestsdk.configure({
    "mode": "sandbox",
    "client_id": paypal_client_id,
    "client_secret": paypal_client_secret
})


def admin_id_required(f):

  @wraps(f)
  def decorated_function(*args, **kwargs):
    user = current_user
    if not user:
      flash("No tan rapido vaquero.", "danger")
      return redirect(url_for("auth.login"))

    expected_user_id = 1
    if user.id != expected_user_id:
      flash("Nu-uh.", "danger")
      return redirect(url_for("views.home"))

    return f(*args, **kwargs)

  return decorated_function


@auth.route("/login", methods=["GET", "POST"])
def login():
  nobars = True
  if request.method == "POST":
    email = request.form.get("email")
    password = request.form.get("password")

    user = User.query.filter_by(email=email).first()
    if user:
      if password:
        if check_password_hash(user.password, password):
          login_user(user, remember=True)
          flash(f"Bienvenid@, {user.username}!", category="success")
          return redirect(url_for("views.home"))
        else:
          flash("Contraseña incorrecta.", category="danger")
    else:
      flash("Usuario no existe.", category="danger")

  return render_template("login.html", user=current_user, nobars=nobars)


@auth.route("/logout")
@login_required
def logout():
  logout_user()
  flash("Te extrañaremos!", category="success")
  return redirect(url_for("views.home"))


@auth.route("/sign_up", methods=["GET", "POST"])
def sign_up():
  nobars = True
  if request.method == "POST":
    email = request.form.get("email")
    username = request.form.get("username")
    password1 = request.form.get("password1")
    password2 = request.form.get("password2")

    user = User.query.filter_by(email=email).first()

    if user:
      flash("El correo electronico ya esta registrado.", category="danger")
    elif len(username) < 3:
      flash("Usuario invalido.", category="danger")
    elif len(email) < 10:
      flash("El correo electronico es invalido.", category="danger")
    elif len(password1) < 4:
      flash("La contraseña debe contener almenos 4 caracteres.",
            category="danger")
    elif password1 != password2:
      flash("Las contraseñas no coinciden.", category="danger")
    else:
      new_user = User(
          email=email,
          username=username,
          password=generate_password_hash(password1,
                                          method="scrypt",
                                          salt_length=16),
      )
      db.session.add(new_user)
      db.session.commit()

      user = User.query.filter_by(email=email).first()

      login_user(user, remember=True)
      flash("Cuenta creada exitosamente!", category="success")
      return redirect(url_for("views.home"))

  return render_template("sign_up.html", user=current_user, nobars=nobars)


@auth.route("/change_password", methods=["GET", "POST"])
def change_password():
  nobars = True
  if request.method == "POST":
    email = request.form.get("email")
    password1 = request.form.get("password1")
    password2 = request.form.get("password2")

    if not email or not password1 or not password2:
      flash("Por favor, complete todos los campos.", "danger")
      return render_template("change_password.html",
                             nobars=nobars,
                             user=current_user)

    user = User.query.filter_by(email=email).first()
    if not user:
      flash("No se encontró ningún usuario con ese correo electrónico.",
            "danger")
      return render_template("change_password.html",
                             nobars=nobars,
                             user=current_user)

    if password1 != password2:
      flash("Las contraseñas no coinciden. Inténtalo de nuevo.", "danger")
      return render_template("change_password.html",
                             nobars=nobars,
                             user=current_user)

    password = generate_password_hash(password1,
                                      method="scrypt",
                                      salt_length=16)
    user.password = password
    db.session.commit()

    flash(
        "Contraseña cambiada exitosamente. Inicia sesión con tu nueva contraseña.",
        "success",
    )
    return redirect(url_for("auth.login"))

  return render_template("change_password.html",
                         nobars=nobars,
                         user=current_user)


@auth.route('/process_payment', methods=['POST'])
def process_payment():
  payment_method = request.form.get('payment_method')
  total_price = request.form.get('total_price')
  cart_items = db.session.query(
      Cart,
      Product).join(Product).filter(Cart.user_id == current_user.id).all()
  
  if cart_items:
    if payment_method == 'paypal':
      return redirect(url_for('auth.paypal_checkout', total_price=total_price))
    if payment_method == 'email':
      return redirect(url_for('auth.email_checkout', total_price=total_price))
    if payment_method == 'whatsapp':
      return redirect(url_for('auth.whatsapp_checkout', total_price=total_price))
    else:
      flash("Algo salio mal :(", "danger")
      return redirect(url_for("views.cart"))
  else:
    flash("Selecciona un producto para añadir al carrito.", "danger")
  return redirect(url_for("views.home"))
  


@auth.route("/paypal_checkout/<total_price>")
@login_required
def paypal_checkout(total_price):
  cart_items = db.session.query(
      Cart,
      Product).join(Product).filter(Cart.user_id == current_user.id).all()

  item_descriptions = [
      f"{cart_item.Cart.quantity} {cart_item.Product.product}"
      for cart_item in cart_items
  ]

  transaction_description = ", ".join(item_descriptions)
  transaction_amount = float(total_price)

  payment = paypalrestsdk.Payment({
      "intent":
      "sale",
      "payer": {
          "payment_method": "paypal",
      },
      "transactions": [{
          "amount": {
              "total": transaction_amount,
              "currency": "USD",
          },
          "description": transaction_description,
      }],
      "redirect_urls": {
          "return_url": url_for('auth.success', _external=True),
          "cancel_url": url_for('auth.cancel', _external=True),
      },
  })

  if payment.create():
    try:
      for link in payment.links:
        if link.rel == "approval_url":          
          return redirect(link.href)

      flash("No approval URL found.", "danger")
    except Exception as e:
      db.session.rollback()
      flash(str(e), "danger")

    return redirect(url_for('views.cart'))
  else:
    flash("Creación de pago fallida.", "danger")
    return redirect(url_for('views.home'))
  

@auth.route("/success")
def success():  
  user = User.query.filter_by(id=current_user.id).first()
  client_email = user.email
  my_email = "donfernandogm@gmail.com"
  subject = f"Pedido para {user.username}"
  cart_items = db.session.query(
      Cart,
      Product).join(Product).filter(Cart.user_id == current_user.id).all()

  item_descriptions = [
      f"{cart_item.Cart.quantity} {cart_item.Product.product}"
      for cart_item in cart_items
  ]

  total_price = 0.0

  for cart_item in cart_items:
      if cart_item.Cart.quantity > 0:
          product = Product.query.get(cart_item.Product.id)

          item_price = float(
              product.price * (1 - product.deal / 100) if product.deal != 0 else product.price
          ) * cart_item.Cart.quantity

          total_price += item_price

  total_price = "{:.2f}".format(total_price)

  transaction_description = ", ".join(item_descriptions)
  transaction_amount = float(total_price)

  message = f"Se ha realizado una compra con los siguientes detalles: Descripción: {transaction_description}, Monto: ${transaction_amount:.2f}. Estaremos en contacto para la entrega de sus productos o la planificación de sus servicios."

  msg = MIMEMultipart('alternative')
  msg['Subject'] = subject
  msg['From'] = my_email
  msg['To'] = client_email

  part1 = MIMEText(message, 'plain')

  msg.attach(part1)

  try:
    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login('donfernandogm@gmail.com', 'zuzb xxbp pvum yzeb')

    server.sendmail(client_email, my_email, msg.as_string())
    server.quit()

    Cart.query.filter_by(user_id=current_user.id).delete()
    db.session.commit()
    
    for cart_item in cart_items:
      product = cart_item.Product
      product.quantity -= cart_item.Cart.quantity
      
    flash("¡Gracias por preferirnos!", "success")
    return redirect(url_for("views.cart"))
  except Exception as e:
    flash(f"Error al enviar el correo. Error: {str(e)}", "danger")
    return redirect(url_for('views.cart'))



@auth.route("/cancel")
def cancel():
  return redirect(url_for("views.cart"))


@auth.route('/email_checkout/<total_price>')
def email_checkout(total_price):
  user = User.query.filter_by(id=current_user.id).first()
  client_email = user.email
  my_email = "donfernandogm@gmail.com"
  subject = f"Solicitud de pedido para {user.username}"
  cart_items = db.session.query(
      Cart,
      Product).join(Product).filter(Cart.user_id == current_user.id).all()

  item_descriptions = [

website/templates/admin.html
{% extends "base.html" %} {% block title %}Administrador{% endblock %} {% block
content %}

<h1 class="mt-2 mb-3" style="padding-top: 160px">Panel de administrador</h1>
<div class="row text-center mb-5 align-items-center justify-content-center">
  <div class="col-md-3 my-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Editar etiquetas</h5>
        <a href="{{ url_for('views.tags') }}" class="btn btn-primary"
          >Ir a la página</a
        >
      </div>
    </div>
  </div>
  <div class="col-md-3 my-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Gestionar usuarios</h5>
        <a href="{{ url_for('views.manage_users') }}" class="btn btn-primary"
          >Ir a la página</a
        >
      </div>
    </div>
  </div>
  <div class="col-md-3 my-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Añadir productos</h5>
        <a href="{{ url_for('views.add_product') }}" class="btn btn-primary"
          >Ir a la página</a
        >
      </div>
    </div>
  </div>
  <div class="col-md-3 my-3">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Editar productos</h5>
        <a href="{{ url_for('views.edit_product') }}" class="btn btn-primary"
          >Ir a la página</a
        >
      </div>
    </div>
  </div>
</div>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/delvarg_logo.png') }}"
      type="image/x-icon"
    />
    <title>{% block title %}DELVARG base{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
      integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='bootstrap-5.3.2-dist/css/bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
  </head>
  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white py-4 fixed-top">
      <div class="container">
        <a
          class="navbar-brand d-flex justify-content-between align-items-center order-lg-0"
          href="{{ url_for('views.home') }}"
        >
          <img
            src="{{ url_for('static', filename='images/delvarg_logo_black.png') }}"
          />
          <span class="text-uppercase fw-lighter ms-2">DELVARG</span>
        </a>

        <div class="order-lg-2 nav-btns">
          {% if user.is_authenticated and not user.id == 1 %}
          <a href="{{ url_for('views.cart') }}">
            <button type="button" class="btn position-relative">
              <i class="fa fa-shopping-cart"></i>
              {% if cart_count != 0 %}
              <span
                class="position-absolute top-0 start-100 translate-middle badge bg-primary"
                >{{ cart_count }}</span
              >
              {% endif %}
            </button></a
          >

          <a href="{{ url_for('views.heart') }}"
            ><button type="button" class="btn position-relative">
              <i class="fa fa-heart"></i>
              {% if heart_count != 0 %}
              <span
                class="position-absolute top-0 start-100 translate-middle badge bg-primary"
                >{{ heart_count }}</span
              >
              {% endif %}
            </button></a
          >

          <a href="{{ url_for('auth.logout') }}"
            ><button type="button" class="btn position-relative">
              <i class="fa fa-right-from-bracket"></i></button
          ></a>

          {% elif user.id == 1 %}

          <a href="{{ url_for('views.admin') }}"
            ><button type="button" class="btn position-relative">
              <i class="fa fa-edit"></i></button
          ></a>
          <a href="{{ url_for('auth.logout') }}"
            ><button type="button" class="btn position-relative">
              <i class="fa fa-right-from-bracket"></i></button
          ></a>

          {% else %}

          <a href="{{ url_for('auth.login') }}"
            ><button type="button" class="btn position-relative">
              <i class="fa fa-right-to-bracket"></i></button
          ></a>

          <a href="{{ url_for('auth.sign_up') }}"
            ><button type="button" class="btn position-relative">
              <i class="fa fa-user-plus"></i></button
          ></a>

          {% endif %}
        </div>

        {% if not nobars %}
        <button
          class="navbar-toggler border-0"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navMenu"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse order-lg-1" id="navMenu">
          <ul class="navbar-nav mx-auto text-center">
            <li class="nav-item px-2 py-2">
              <a class="nav-link text-uppercase text-dark" href="#header"
                >inicio</a
              >
            </li>
            <li class="nav-item px-2 py-2">
              <a class="nav-link text-uppercase text-dark" href="#collection"
                >colección</a
              >
            </li>
            <li class="nav-item px-2 py-2">
              <a class="nav-link text-uppercase text-dark" href="#special"
                >especiales</a
              >
            </li>
            <li class="nav-item px-2 py-2">
              <a class="nav-link text-uppercase text-dark" href="#blogs"
                >blogs</a
              >
            </li>
            <li class="nav-item px-2 py-2">
              <a
                class="nav-link text-uppercase text-dark"
                href="{{ url_for('views.faq') }}"
                >faq</a
              >
            </li>
            <li class="nav-item px-2 py-2">
              <a class="nav-link text-uppercase text-dark" href="#about"
                >sobre nosotros</a
              >
            </li>
          </ul>
        </div>
        {% else %}
        <div class="collapse navbar-collapse order-lg-1" id="navMenu">
          <ul class="navbar-nav mx-auto text-center">
            <li class="nav-item px-2 py-3">
              <a class="text-uppercase text-white"
                >codigo promo: surfeando :D</a
              >
            </li>
          </ul>
        </div>
        {% endif %}
      </div>
    </nav>

    <!-- flashing -->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}

    <div
      id="flash-container"
      class="sticky-flash"
      style="display: none; padding-top: 50px"
    >
      <div id="flash-message" class="alert alert-{{ category }}">
        <span id="flash-text">{{ message }}</span>
        <button id="close-flash" class="close" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    {% endfor %} {% endif %} {% endwith %}

    <!-- content -->
    <div class="container">{% block content %} {% endblock %}</div>

    <!-- footer -->
    <footer class="py-5" style="background-color: rgb(226, 226, 226)">
      <div class="container">
        <div class="row g-4">
          <div class="col-md-8 col-lg-4" style="padding-right:50px">
            <h5 class="fw-light mb-3">Delvarg</h5>
            <p class="text-white text-muted mt-3">
              Para cualquier consulta o comentario, no dudes en ponerte en
              contacto con nosotros. Estamos aquí para ayudarte en cada paso de
              tu viaje.
            </p>
          </div>

          <div class="col-md-8 col-lg-5" style="padding-right:30px">
            <h5 class="fw-light mb-3">Contáctanos</h5>
            <div
              class="d-flex justify-content-start align-items-start my-2 text-muted"
            >
              <span class="me-3">
                <i class="fas fa-map-marked-alt"></i>
              </span>
              <span class="fw-light"
                >Calle principal, Via Mataruca, Sector la Alcabala, Lagunetica,
                Municipio Guaicaipuro, <br />
                Estado Bolivariano de Miranda, Venezuela.
              </span>
            </div>
            <div
              class="d-flex justify-content-start align-items-start my-2 text-muted"
            >
              <span class="me-3">
                <i class="fas fa-envelope"></i>
              </span>
              <span class="fw-light">invdelvarg28@gmail.com</span>
            </div>
            <div
              class="d-flex justify-content-start align-items-start my-2 text-muted"
            >
              <span class="me-3">
                <i class="fas fa-phone-alt"></i>
              </span>
              <span class="fw-light"> +0424 271 7296 </span>
            </div>
          </div>

          <div class="col-md-8 col-lg-2">
            <h5 class="fw-light mb-3">Síguenos</h5>
            <div>
              <ul class="list-unstyled d-flex">
                <li>
                  <a
                    href="https://www.facebook.com/MegaMundo.es"
                    class="text-white text-decoration-none text-muted fs-4 me-4"
                  >
                    <i class="fab fa-facebook"></i>
                  </a>
                </li>
                <li>
                  <a
                    href="https://www.instagram.com/inversionesdelvarg/"
                    class="text-white text-decoration-none text-muted fs-4 me-4"
                  >
                    <i class="fab fa-instagram"></i>
                  </a>
                </li>
                <li>
                  <a
                    href="https://wa.me/message/ZJJ2XVA67OTQN1"
                    class="text-white text-decoration-none text-muted fs-4 me-4"
                  >
                    <i class="fab fa-whatsapp"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <!-- scripts -->
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/jquery-3.7.1.js') }}"
    ></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.js"></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='bootstrap-5.3.2-dist/js/bootstrap.min.js') }}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/script.js') }}"
    ></script>
  </body>
</html>

website/templates/change_password.html
{% extends "base.html" %} {% block title %}Actualiza la contraseña{% endblock %}
{% block content %}
<div class="row justify-content-center" style="padding-top: 180px">
  <div class="col-md-6">
    <h2 class="text-center mb-4">Actualiza tu contraseña</h2>
    <form method="POST">
      <div class="mb-4">
        <label for="email" class="form-label">Correo Electrónico</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          required
        />
      </div>
      <div class="mb-4">
        <label for="password" class="form-label">Nueva contraseña</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          required
        />
      </div>
      <div class="mb-4">
        <label for="confirm_password" class="form-label"
          >Confirmar contraseña</label
        >
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          required
        />
      </div>
      <div class="text-center">
        <button
          type="submit"
          class="btn btn-primary mt-3"
          style="margin-bottom: 60px"
        >
          Aceptar
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

website/templates/edit_tags.html
{% extends "base.html" %} {% block title %}Editar etiquetas{% endblock %} {%
block content %}

<div class="row" style="padding: 170px 0px 100px 0px">
  <div class="col-md-6">
    <h3>Añadir etiquetas principales:</h3>
    <form method="POST" action="{{ url_for('views.tags') }}" class="mb-5">
      <div class="input-group">
        <input
          type="text"
          class="form-control"
          style="border-top-left-radius: 25px; border-bottom-left-radius: 25px"
          name="main_tag"
          id="main_tag"
          required
        />
        <button class="btn btn-primary" type="submit">Añadir</button>
      </div>
    </form>

    <h3 class="mt-4">Añadir etiquetas secundarias:</h3>
    <form method="POST" action="{{ url_for('views.tags') }}" class="mb-5">
      <div class="input-group">
        <select
          class="form-select text-center text-capitalize"
          name="main_tag_id"
          style="
            border-top-left-radius: 25px;
            border-bottom-left-radius: 25px;
            max-width: 200px;
          "
          required
        >
          {% for main_tag in main_tags %}
          <option value="{{ main_tag.id }}" class="text-capitalize">
            {{ main_tag.tag_name }}
          </option>
          {% endfor %}
        </select>
        <input
          type="text"
          class="form-control col-md-6"
          name="secondary_tag"
          id="secondary_tag"
          required
        />
        <button
          class="btn btn-primary col-md-2"
          type="submit"
          style="padding: 10px 0px"
        >
          Añadir
        </button>
      </div>
    </form>
  </div>

  <div class="col-md-6" style="padding-left: 50px">
    <h3>Etiquetas existentes:</h3>
    <ul class="list-group" style="width: 350px">
      {% for main_tag in main_tags %}
      <li class="list-group-item text-capitalize">
        {{ main_tag.tag_name }}
        <a
          href="{{ url_for('views.delete_tag', tag_id=main_tag.id) }}"
          class="btn-outline-none"
          style="
            color: #e5345b;
            border-color: rgb(255, 255, 255, 0);
            background-color: rgb(255, 255, 255, 0);
            padding-left: 15px;
          "
        >
          <i class="fas fa-trash"></i>
        </a>
        <ul class="list-group mt-2">
          {% for secondary_tag in main_tag.child_tags %}
          <li class="list-group-item">
            {{ secondary_tag.tag_name }}
            <a
              href="{{ url_for('views.delete_tag', tag_id=secondary_tag.id) }}"
              class="btn-outline-none"
              style="
                color: #e5345b;
                border-color: rgb(255, 255, 255, 0);
                background-color: rgb(255, 255, 255, 0);
                padding-left: 15px;
              "
            >
              <i class="fas fa-trash"></i>
            </a>
          </li>
          {% endfor %}
        </ul>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% endblock %}

website/templates/faq.html
{% extends "base.html" %} {% block title %}Preguntas Frecuentes{% endblock %} {%
block content %}

<h1 style="padding-top: 170px">Preguntas Frecuentes</h1>
<div class="accordion my-5" id="accordionFaq">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button
        class="accordion-button"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#collapseOne"
        aria-expanded="false"
        aria-controls="collapseOne"
      >
        ¿Como puedo registrarme?
      </button>
    </h2>
    <div
      id="collapseOne"
      class="accordion-collapse collapse show"
      data-bs-parent="#accordionFaq"
    >
      <div class="accordion-body">
        Navega hacia la pagina de registro de usuarios y rellena todos los
        campos. Luego haz clic en el boton "Aceptar".
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button
        class="accordion-button collapsed"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#collapseTwo"
        aria-expanded="false"
        aria-controls="collapseTwo"
      >
        ¿Como cambiar mi contraseña?
      </button>
    </h2>
    <div
      id="collapseTwo"
      class="accordion-collapse collapse"
      data-bs-parent="#accordionFaq"
    >
      <div class="accordion-body">
        Haz clic <a href="{{ url_for('auth.change_password') }}">aqui</a> y
        llena el formulario.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button
        class="accordion-button collapsed"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#collapseThree"
        aria-expanded="false"
        aria-controls="collapseThree"
      >
        ¿Como quito un producto de mi carrito de compras?
      </button>
    </h2>
    <div
      id="collapseThree"
      class="accordion-collapse collapse"
      data-bs-parent="#accordionFaq"
    >
      <div class="accordion-body">
        Navega hacia la pagina de carrito de compras y haz clic en el boton
        "Eliminar" justo abajo del producto que quieras eliminar.
      </div>
    </div>
  </div>
</div>

{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Iniciar sesión{% endblock %} {% block
content %}
<div class="row justify-content-center" style="padding-top: 180px">
  <div class="col-md-6">
    <h1 class="text-center mb-4">Iniciar sesión</h1>
    <form method="POST">
      <div class="mb-4">
        <label for="email" class="form-label">Correo electrónico</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          required
        />
      </div>
      <div class="mb-2">
        <label for="password" class="form-label">Contraseña</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          required
        />
      </div>
      <a
        href="{{ url_for('auth.sign_up') }}"
        style="text-decoration: none; font-size: 15px"
        ><span style="color: rgb(0, 0, 0)">¿No tienes una cuenta aún?</span>
        ¡Crea una ahora mismo!</a
      ><br />
      <a
        href="{{ url_for('auth.change_password') }}"
        style="text-decoration: none; font-size: 15px"
        ><span style="color: rgb(0, 0, 0)">¿Se te olvido tu contraseña?</span>
        Haz clic aquí para cambiarla.</a
      >
      <div class="text-center">
        <button
          type="submit"
          class="btn btn-primary mt-5"
          style="margin-bottom: 60px"
        >
          Aceptar
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

website/templates/manage_users.html
{% extends "base.html" %} {% block title %}Editar producto{% endblock %} {%
block content %}

<div class="container mb-5">
  <h2 class="text-center my-4" style="padding-top: 140px">
    Gestionar usuarios
  </h2>

  {% for user in users %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">{{ user.username }}</h5>
      <p class="card-text">Email: {{ user.email }}</p>
      <form method="POST">
        <input
          type="hidden"
          id="user_id"
          name="user_id"
          value="{{ user.id }}"
        />
        <button type="submit" class="btn btn-danger">Eliminar usuario</button>
      </form>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}